# Generated by Django 4.2.30 on 2026-04-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full project name (e.g. 'BiodiversityGenomicsEurope')", max_length=300, unique=True)),
                ('rcode', models.CharField(blank=True, help_text='University R-code (finance reference), e.g. R127778', max_length=50)),
                ('is_active', models.BooleanField(blank=True, help_text='Is this project currently active?', null=True)),
                ('is_ts_required', models.BooleanField(blank=True, help_text='Does this project require timesheets?', null=True, verbose_name='Timesheet (TS) required?')),
                ('is_audited', models.BooleanField(blank=True, help_text='Is this project subject to external audit?', null=True, verbose_name='Audit required?')),
                ('pm_original', models.FloatField(blank=True, help_text='Originally allocated person-months', null=True)),
                ('pm_additional', models.FloatField(blank=True, help_text='Additional person-months added later', null=True)),
                ('pm_used', models.FloatField(blank=True, help_text='Person-months already used/recorded', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Project end date', null=True)),
                ('work_type', models.CharField(blank=True, help_text="Type of work (e.g. 'EU Horizon', 'UKRI')", max_length=200)),
                ('possible_staff', models.TextField(blank=True, help_text='Free-text notes on who could work on this project')),
                ('notes', models.TextField(blank=True, help_text='General notes about this project')),
            ],
            options={
                'ordering': ['end_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(help_text="Short identifier used across the spreadsheet (e.g. 'SS', 'MA')", max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full name of the staff member', max_length=200)),
                ('staff_type', models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Research', 'Research Staff'), ('PS', 'Professional Services')], help_text='Academic, Research, or Professional Services', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department/Group (e.g. CS/eSL, IT/RIT)', max_length=100)),
                ('pcm_until', models.DateField(blank=True, help_text="Date until which the staff member's PCM (People Cost Model) runs", null=True)),
                ('timesheets_approved_until', models.DateField(blank=True, help_text='Month up to which timesheets have been approved/submitted', null=True)),
                ('notes', models.TextField(blank=True, help_text="Free-text notes about this staff member's arrangements")),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(help_text='Start of the period this cost applies')),
                ('valid_until', models.DateField(help_text='End of the period this cost applies')),
                ('monthly_cost', models.DecimalField(decimal_places=2, help_text='Monthly cost in £ (salary + on-costs)', max_digits=10)),
                ('confidence', models.CharField(blank=True, help_text="How accurate is this figure? (e.g. 'Approx', 'Close', 'Exact')", max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Source or explanation of this cost figure')),
                ('staff_member', models.ForeignKey(help_text='Which staff member this cost applies to', on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='planning.staffmember')),
            ],
            options={
                'ordering': ['staff_member', 'valid_from'],
            },
        ),
        migrations.CreateModel(
            name='StaffAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start of this allocation period')),
                ('end_date', models.DateField(help_text='End of this allocation period')),
                ('fte', models.FloatField(help_text='Fraction of full-time worked on this project (e.g. 0.5 = 50%)')),
                ('person_months', models.FloatField(blank=True, help_text='Total person-months for this allocation (FTE × months)', null=True)),
                ('hours_per_month', models.FloatField(blank=True, help_text='Hours per month worked on this project', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost (£) of this allocation period', max_digits=12, null=True)),
                ('work_packages', models.CharField(blank=True, help_text="Which Work Packages this person is working on (e.g. 'WP2, WP3')", max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Any notes about this particular allocation')),
                ('project', models.ForeignKey(help_text='Which project they are allocated to', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='planning.project')),
                ('staff_member', models.ForeignKey(help_text='Which person is allocated', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='planning.staffmember')),
            ],
            options={
                'ordering': ['staff_member', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_di_original', models.DecimalField(blank=True, decimal_places=2, help_text='Originally awarded budget for directly-incurred staff costs', max_digits=12, null=True, verbose_name='Original DI (A01) budget £')),
                ('budget_da_original', models.DecimalField(blank=True, decimal_places=2, help_text='Originally awarded budget for directly-allocated staff costs', max_digits=12, null=True, verbose_name='Original DA (A12) budget £')),
                ('budget_additional', models.DecimalField(blank=True, decimal_places=2, help_text='Any additional budget awarded', max_digits=12, null=True)),
                ('project', models.OneToOneField(help_text='The project this budget belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='planning.project')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_project_name', models.CharField(blank=True, max_length=300)),
                ('to_project_name', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(blank=True, help_text='When the swap occurred', null=True)),
                ('amount_gbp', models.DecimalField(blank=True, decimal_places=2, help_text='Amount transferred in £', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Reason for the swap')),
                ('action_to_balance', models.TextField(blank=True, help_text='What needs to happen to settle this')),
                ('from_project', models.ForeignKey(blank=True, help_text='Project that is paying / giving up budget', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swaps_out', to='planning.project')),
                ('to_project', models.ForeignKey(blank=True, help_text='Project that receives the budget', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swaps_in', to='planning.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_number', models.CharField(help_text="Work Package identifier (e.g. 'WP1', 'WP3')", max_length=20)),
                ('title', models.CharField(blank=True, help_text='Full title of this Work Package', max_length=500)),
                ('person_months', models.FloatField(blank=True, help_text='Total person-months allocated to this Work Package', null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(help_text='The project this Work Package belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='work_packages', to='planning.project')),
            ],
            options={
                'ordering': ['project', 'wp_number'],
                'unique_together': {('project', 'wp_number')},
            },
        ),
    ]
