# Generated by Django 4.2.30 on 2026-04-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='employee_number',
            field=models.CharField(blank=True, help_text='University employee/staff ID number (e.g. 5030408)', max_length=20),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='pcm_projected_until',
            field=models.DateField(blank=True, help_text='Projected (estimated) date until which PCM may run — may extend beyond confirmed date', null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='pcm_until',
            field=models.DateField(blank=True, help_text="Confirmed date until which the staff member's PCM runs", null=True),
        ),
    ]
